services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    container_name: supabase-crm-db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      # Add your external Supabase credentials here:
      
      # Add any additional environment variables below:
      # - DATABASE_URL=postgresql://...
      #Testing
    volumes:
      # Mount workspace directory for Hot Module Replacement (HMR)
      - .:/app
      # Prevent local host node_modules from overriding container node_modules
      - /app/node_modules
      - /app/.next
